name: Complete CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/torbenjohnson/advent_of_code-ci:latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust version
        run: rustc --version

      - name: Run just ci
        run: just ci
